//
//  Affirmations.",swift
//  YourSteps
//
//  Created by TaeVon Lewis on 6/1/23.",
//

import Foundation

let affirmations = [
    "Wealth": [
        "I am a magnet for money..",
        "I deserve to make more money..",
        "I have great wealth and live in abundance..",
        "Wealth is drawn to me..",
        "I have more than enough money..",
        "I am ready to receive an abundance of money..",
        "My income is growing higher and higher..",
        "Money easily flows to me..",
        "I allow my income to expand constantly..",
        "The Universe supplies me with more than enough money..",
        "My bank balance increases daily..",
        "Abundance is constantly attracted to me..",
        "I easily find more ways to generate money..",
        "I easily pay my pills..",
        "My savings continually grows..",
        "Money is never away from me..",
        "I have an abundance mindset..",
        "Making money is easy..",
        "My net worth grows greater and greater..",
        "My income automatically increases higher and higher..",
        "I welcome money into my life..",
        "I have (amount of money) dollars in my bank account..",
        "I can afford the lifestyle that I want..",
        "My middle name is money..",
        "I am wealthier than I could ever imagine..",
        "I am a lender, not a borrower..",
        "I can donate an amazing amount of money..",
        "I change people’s lives with my income..",
        "Every activity I perform, makes me money..",
        "Making money is amazingly easy for me..",
        "Money is being delivered..",
        "My bank account is full of money..",
        "I place no limits on the amount of money I can make..",
        "I have an endless supply of cash..",
        "Money is attracted to me everywhere I go..",
        "I am wealthy doing what I love..",
        "I enjoy making lots of money..",
        "I am receiving financial fortune..",
        "I am totally debt-free..",
        "I enjoy my prosperous life..",
        "My income far exceeds my expenses..",
        "I enjoy my abundant life..",
        "Money comes to me from unexpected sources..",
        ",The Universe has an endless amount of money..",
        "I make money in unexpected ways..",
        "My investments continually make an abundance of money..",
        "I live in a rich and giving Universe..",
        "I am benefiting from an abundant Universe..",
        "I feel deserving of having lots of money..",
        "There is plenty of wealth for all of us..",
        "I can easily help those that are less fortunate than me..",
        "I accumulate wealth easily..",
        "Large sums of money flow easily to me..",
        "I enjoy a luxurious lifestyle..",
        "I can buy anything I want..",
        "My wealth allows me the freedom to do what I want when I want..",
        "I have multiple houses and cars..",
        "I live a lifestyle of luxury..",
        "I am amazingly rich..",
        "I am extremely wealthy..",
        "I have more money than I know what to do with..",
        "I earn (amount of dollars) a month easily..",
        "My business earns (amount of dollars) every month..",
        "I make at least (amount of dollars) a year..",
        "The more money I spend, the more money I make..",
        "There is always more money coming to me..",
        "My money works for me easily and efficiently..",
        "I increase my money and abundance daily..",
        "I provide wealth for my family..",
        "I give my family a life of luxury..",
        "My money is a source of good for others and myself..",
        "I feel good about my wealth..",
        "I’m living my destiny to be wealthy..",
        "I deserve a rich life..",
        "I am thankful for the money I have..",
        "I release all negative feelings about money that I have..",
        "I deserve to be financially free..",
        "I am grateful to be financially free..",
        "I experience no limits in wealth..",
        "Money flows to me in ways I couldn’t imagine..",
        "The more money I have, the more I can give..",
        "I experience a waterfall of money..",
        "I welcome all the things money can buy..",
        "I pay my bills easily and with joy..",
        "Money is finding ways into my life..",
        "I let go of all my fears about money..",
        "I spend money without fear or guilt..",
        "I have all the skills and abilities I need right now to generate wealth..",
        "I am grateful for the money that I now have..",
        "The Universe deems me worthy of being rich..",
        "I am open to an infinite amount of wealth..",
        "I have more than enough money needed for all the things I desire..",
        "I am the master of my money..",
        "There are no limits to the amount of money that flows to me..",
        "I am open and receptive to all the money in the Universe..",
        "Prosperity of every kind is drawn to me..",
        "I have more wealth than yesterday, and I will be more wealthy tomorrow..",
        "Every day brings me more wealth and abundance..",
        "It’s in my nature to be wealthy..",
        "I create wealth easily..",
    ],
    "Happy Life": [
        "I am a vessel of happiness.",
        "I deserve to be happy.",
        "I am worthy of love and joy.",
        "I deserve to be successful and happy.",
        "I am responsible for my happiness, no one else is.",
        "I create my own happiness in life.",
        "I act in all things with confidence.",
        "I forgive myself completely.",
        "I choose to be happy.",
        "I have the power to be happy no matter the circumstance.",
        "The Universe is working for me.",
        "The Universe is delivering health, wealth, and prosperity.",
        "I release all the hurt that was done to me.",
        "I forgive everyone who has ever wronged me.",
        "Happiness exists everywhere I go.",
        "I release all negativity.",
        "I accept all the good that is in my life.",
        "Happy thoughts bring positive outcomes.",
        "I have a positive outlook no matter the situation.",
        "I live a life of abundance and joy.",
        "I have fun working towards my goal.",
        "I make others around me happy.",
        "I am cheerful naturally.",
        "I have habits that manifest happiness in my life.",
        "Every cell in my body radiates happiness.",
        "Every day in every way I’m getting better and better.",
        "I always have a reason to smile.",
        "I easily enjoy every moment.",
        "I always follow my heart.",
        "I have a great sense of humor.",
        "Peace is my middle name.",
        "I am joyous about my opportunities.",
        "Great opportunities present themselves to me every day.",
        "My choices are wise and sound.",
        "I am satisfied with the decisions I make.",
        "I accept happiness into my life.",
        "I wake up in a positive mood.",
        "I am grateful for everything I have in life.",
        "I enjoy every breath I take.",
        "I allow myself to laugh and be silly.",
        "I brighten the mood every time I enter a room.",
        "I am joyful for even the simplest of things.",
        "I take the time to be mindful of my surroundings.",
        "I am responsible for my own joy.",
        "The power to be happy relies in only me.",
        "I have everything I need inside to live a happy fulfilling life.",
        "I love who I am.",
        "I love to have fun.",
        "It’s okay to have fun.",
        "I know that happiness comes from great habits.",
        "I can create my own true happiness.",
        "I laugh frequently and freely.",
        "I make time for things that make me happy.",
        "I feed my body and mind with positive thoughts.",
        "I only speak positively.",
        "I see the good in all things and situations.",
        "I spread joy to everyone I meet.",
        "I smile at everyone I walk by.",
        "I do something that brings me joy every day.",
        "I feel okay about doing things just for me.",
        "It’s okay for me to give of myself.",
        "I welcome into my life an abundance of joy.",
        "It brings me great joy to do for others.",
        "It is my birthright to live a happy and prosperous life.",
        "Joy comes easy for me.",
        "I only attract joyful and happy people into my life.",
        "My love of life spreads to others.",
        "I empty my mind of all negative thoughts.",
        "I am superior to negative thoughts.",
        "I am in complete control over my emotions.",
        "I have everything I need to succeed.",
        "Every day, I am overflowing with joy.",
        "Creative energy flows inside and around me.",
        "I can overcome any obstacle that stands in my way.",
        "My thoughts are filled with positivity.",
        "I am admired by those who meet and know me.",
        "I realize that everything that happens is for a reason.",
        "The Universe is causing my desires to manifest.",
        "The Universe is delivering freedom and happiness.",
        "I radiate beauty.",
        "I am easily conquering my sickness.",
        "I wake up strong and motivated.",
        "Every day is more joyful than the last.",
        "I always find the positive in everything.",
        "I think very highly of myself because it is deserved.",
        "It’s easy to overcome negative thoughts and emotions.",
        "I utilize my compassion and forgiveness to the fullest degree.",
        "Thinking positive is a natural part of who I am.",
        "My positivity transforms my reality.",
        "I can do anything I want.",
        "There are no limits to the amount of happiness I can experience.",
        "I see how good this world really is.",
        "I keep my worries under control.",
        "I easily overcome stress and anxiety.",
        "I am living an excellent life.",
        "I am thankful for all that I have.",
        "I will always have a positive outlook and will always be optimistic.",
        "My glass is always half full.",
        "I choose to think of myself and others in a positive light.",
        "Great things always come my way.",
    ],
    "Healthy Body and Mind": [
        "Every day I am getting healthier and healthier.",
        "I am full of energy and vitality.",
        "I crave healthy and nutritious foods that benefit my body.",
        "Good health is my birthright.",
        "I am strong in mind and body.",
        "Every day my body gains more energy and vitality.",
        "I am free of ailments, disease, and all life-threatening conditions.",
        "My blood pressure and cholesterol levels are exemplary.",
        "I easily take care of my body.",
        "I am in great shape, and in great health.",
        "I have an abundant supply of energy.",
        "I deserve to have great health.",
        "I am attracting a life of amazing health.",
        "I am easily getting healthier, every single day.",
        "I take care of my body with love and respect.",
        "I am easily losing weight.",
        "It’s easy for me to exercise and eat right.",
        "I live an incredibly healthy lifestyle.",
        "I have an endless amount of motivation.",
        "I am strong.",
        "My lifestyle inspires others to be healthy and fit.",
        "I am in tune with my body’s needs.",
        "I have the ability to heal quickly.",
        "My immune system is strong and powerful.",
        "Every cell in my body is working for me.",
        "My mind is at peace and is calm.",
        "My body is flexible and balanced.",
        "I feel amazing!",
        "My bones, organs, and body systems are in perfect health.",
        "I awake each day refreshed and full of energy.",
        "I am in the best health of my life.",
        "I adopt great healthy habits easily.",
        "I always eat healthily.",
        "I crave only foods that are good for my body.",
        "I am dedicated to having great health.",
        "I recover quickly and easily from an illness.",
        "My body is resilient against sickness.",
        "Every day I am becoming stronger.",
        "I can overcome any health obstacle.",
        "I enjoy working out and exercising.",
        "I weigh what I’m supposed to weigh.",
        "Overcoming an illness is easy.",
        "I deserve to be healthy and happy.",
        "I have a positive attitude towards my body.",
        "My mind, body, and spirit are strong.",
        "I am free from stress and anxiety.",
        "I let go of my worries easily.",
        "I am easily releasing all tension.",
        "I am in control of my stress levels.",
        "I am in complete control of my emotions.",
        "I am a positive person.",
        "My mind is sharp and focused.",
        "I am laser-focused on keeping my body healthy and fit.",
        "I find it easy to think positively.",
        "I am a great runner.",
        "I enjoy improving my health.",
        "I easily exercise every day.",
        "My heart beats strong.",
        "I radiate energy and joy to those around me.",
        "I am an amazing example of what it means to be healthy and fit.",
        "I live, eat and breathe fitness.",
        "My back and joints are free of pain.",
        "My body is pain-free.",
        "I am in control of pain.",
        "My skin is radiant and healthy.",
        "I look younger and younger every day.",
        "My body is fit and my mind is brilliant.",
        "My body can overcome any obstacle.",
        "I am excited to take care of my body.",
        "I love who I am.",
        "I am a health freak.",
        "I am attracted to foods that heal and cleanse my body.",
        "I treat my body as a temple.",
        "I trust the signals my body sends.",
        "My body is attuned to the wisdom of the universe.",
        "My resilient immune system easily eliminates unhealthy bacteria and viruses.",
        "I am unstoppable.",
        "The healing powers of my body grow each day.",
        "Devine energy flows through my mind.",
        "Every cell in my body is moving towards greater health.",
        "My mind is clear.",
        "Every day brings me improved health.",
        "I choose to live healthy every day of my life.",
        "I am free of ailments and pain.",
        "My (injured body part) is healing fast and efficiently.",
        "It is my right to be of sound mind and body.",
        "My (condition) is getting better every day.",
        "I am easily overcoming my (addiction).",
        "Toxins and waste are easily leaving my body.",
        "The energy around my body is positive and strong.",
        "My body is constantly restoring itself.",
        "My eyesight is sharp and clear.",
        "Every breath I take brings me health and healing.",
        "I strengthen my muscles easily.",
        "I easily manifest perfect health.",
        "I find it easy to make smart health choices.",
        "My subconscious attracts all that is good for me.",
        "My body is living long.",
        "I am surrounded by people who encourage me to be healthy.",
    ],
    "Love and Relationships": [
        "I am surrounded by love.",
        "My heart is open with trust.",
        "I have an abundance of love.",
        "My partner and I are perfectly matched.",
        "I can easily understand and accept my partner’s point of view.",
        "I can easily communicate my feelings and point of view to my partner.",
        "The love I give is increased many times when it comes back to me.",
        "My heart is open and receptive to love.",
        "I attract only people who are deserving of me.",
        "I am in a joyous, fulfilling relationship with a person who loves me more than anything.",
        "I am comfortable loving who I am.",
        "I am attracting a lasting relationship.",
        "My soulmate is out there.",
        "I attract positive, loving, people in my life.",
        "I am attracting my soulmate.",
        "My partner and I are a team and our love is unconditional.",
        "I spread joy and love wherever I go.",
        "I welcome love with open arms.",
        "I am irresistible to those around me.",
        "I deserve to love and to be loved.",
        "The more I desire someone the more they are attracted to me.",
        "My inner beauty is shining through.",
        "I love being loved.",
        "I desire love and receive it in abundance.",
        "Loving and being loved is my birthright.",
        "The Universe is finding my perfect match.",
        "I have an abundance of love to give.",
        "I am attractive, I am beautiful, I am desirable.",
        "I love every aspect of my life.",
        "My soul is full of love and warmth.",
        "I am deserving of a joyful, lasting, relationship.",
        "I am surrounded by more love than I ever thought possible.",
        "My partner knows me and loves me flaws and all.",
        "I have a fun and exciting relationship.",
        "My loved one is the love of my life and I am the love of theirs.",
        "My relationship is full of joy and wonder.",
        "My partner loves everything about me.",
        "Positive love is flowing towards me always.",
        "I am faithful, supporting, and loving.",
        "Everywhere I go, love finds me.",
        "My love is faithful and supporting.",
        "My relationship is my priority above all else.",
        "I am attracted to people best for me.",
        "I am everything my partner desires.",
        "Love surrounds me every day in every way.",
        "I have a committed love life.",
        "I enjoy being in a strong, committed relationship.",
        "Love flows towards me and through me.",
        "I am a magnet for true lasting love.",
        "My love is perfect inside and out.",
        "I am confident in my love life.",
        "I am beautiful and loved by everyone.",
        "My relationship is stronger than any obstacle.",
        "I am able and willing to forgive.",
        "I can be me in my relationship.",
        "I am treasured for who I really am.",
        "My marriage is becoming stronger and more loving every day.",
        "My spouse and I are meant to be together.",
        "I am loved and wanted by my partner.",
        "I enjoy my spouse being so attracted to me.",
        "I accept responsibility for my actions and make my wrongs right.",
        "I treat my partner the way I want to be treated.",
        "I give unconditional love.",
        "There is nothing that can come between my partner and I.",
        "My goal is to listen and understand, not to win.",
        "I speak kind, supporting words to my partner.",
        "I communicate my needs clearly and honestly.",
        "I show my loved one often how much I appreciate them.",
        "I am excited for marriage.",
        "I love (enter significant other’s name) and will be there for him/her through thick and thin.",
        "I am open and ready for marriage.",
        "I forgive my ex and recognize the good that did exist.",
        "I will heal from this.",
        "I am grateful that everything happens for a reason.",
        "I release the past.",
        "I am completely whole and happy by myself.",
        "I am attracting the right love.",
        "I effortlessly attract love.",
        "I always have love surrounding me.",
        "I shower my love generously to others.",
        "I show love and compassion with every fiber of my being.",
        "I create love all around me.",
        "I accept and love everything about myself.",
        "I easily express my feelings and emotions.",
        "I am an effective communicator.",
        "I emotionally support my partner.",
        "I am surrounded by people who love and support me.",
        "My partner and I are compatible in every way.",
        "It is easy for me to love.",
        "It is easy for me to accept love.",
        "I am a magnet for great relationships.",
        "Everything I do is out of love.",
        "I attract love from being myself.",
        "I am in love with being in love.",
        "I am an amazing wife.",
        "I am a loving and supporting husband.",
        "I am my partner’s rock through thick and thin.",
        "My partner and I share passionate intimacy.",
        "Every day my spouse and I strengthen our bond.",
        "I am meeting my soulmate today.",
    ],
    "Confidence and Increased Self-esteem": [
        "I am overflowing with confidence.",
        "I am creative, talented, and confident.",
        "I can adapt, grow, and change when necessary with ease.",
        "I take on any challenge that faces me.",
        "Confidence is what I live for.",
        "I recognize my imperfections and accept them fully.",
        "I easily adjust to new situations and circumstances.",
        "I easily make friends.",
        "I am unique and feel great about being me.",
        "Life is full of excitement and fun.",
        "My life is full of amazing opportunities.",
        "I clearly see all opportunities in front of me.",
        "I choose happiness for my life.",
        "I appreciate who I am and love my life.",
        "I create solutions.",
        "I have faith in my skills and abilities.",
        "I am grateful for everything I have been blessed with.",
        "I always act in the face of fear.",
        "My life is fulfilling and full of happiness.",
        "I am the poster child for optimism.",
        "I always face fear with excitement and perseverance.",
        "I create a positive atmosphere everywhere I go.",
        "I trust the person I am becoming.",
        "I am proud of the person I have become.",
        "My enthusiasm rubs off on others.",
        "I take the time to slow down and appreciate life.",
        "I am compassionate, kind and loving towards others.",
        "I inhale confidence and exhale fear.",
        "I am releasing all self-limiting beliefs.",
        "I make friends easily and attract amazing people.",
        "I am calm and full of peace when under pressure.",
        "I deserve to feel good about myself.",
        "I am perfect all by myself.",
        "I make bold and smart choices.",
        "Everything I need to succeed is within me.",
        "I always attract the best circumstances.",
        "I am a victor not a victim.",
        "I understand that every moment I breathe is a gift.",
        "I am deserving of love just the way I am.",
        "I attract peace and love.",
        "I am naturally confident in all that I do.",
        "I easily create habits that are healthy for me.",
        "I am beautiful inside and out.",
        "Fear of failure does not control me.",
        "I am comfortable being who I really am.",
        "My actions are for my future, not because of my past.",
        "I have the power to change.",
        "I am an example of confidence.",
        "I recognize my great qualities.",
        "I see the best in myself and others.",
        "I surround myself with people who support me.",
        "I love the person I have grown to be.",
        "My opinions are important and they matter.",
        "I am full of integrity and discipline.",
        "I can do anything I put my mind to.",
        "I easily accept compliments because I deserve them.",
        "I radiate exceptionalism everywhere I go.",
        "My high self-esteem allows me to shrug off criticism easily.",
        "What matters most is how I react and what I believe.",
        "I respect myself highly.",
        "I release the need to prove myself to others.",
        "I am responsible for my own happiness.",
        "I am well-loved by others.",
        "I am wise and humble.",
        "I am just as good as everyone else.",
        "I release any need to be negative and pessimistic.",
        "My mind is full of positive, loving thoughts.",
        "I release the past, live in the present, and am excited for the future.",
        "I constantly make positive changes in all areas of my life.",
        "I have unlimited potential.",
        "There are no limits before me.",
        "I am a unique gift to the world.",
        "I am here for a reason.",
        "The greatest gift I can receive is my own unconditional love.",
        "I am perfect right now.",
        "I support myself fully and competently.",
        "I body go after what I want in life.",
        "I act swiftly and with energy.",
        "I confidently and respectfully speak my mind.",
        "I have unbreakable confidence.",
        "I am confident and outgoing in social settings.",
        "I am assertive and impressive.",
        "Confidence allows me to overcome procrastination and take action.",
        "I go for what I want without hesitation.",
        "My skills and abilities are enough to do what I want in life.",
        "Being strong, bold and confident is normal for me.",
        "I am free from the fear of failure.",
        "I always get back up and keep going.",
        "I am persistent and disciplined.",
        "I embrace failure and learn from it.",
        "I easily overcome setbacks.",
        "My confidence is unshakeable and is never diminished.",
        "Gaining strength and wisdom from failure comes naturally.",
        "I always succeed because I want to.",
        "I am aware of all my accomplishments.",
        "I give myself permission to fall because I’ll always get back up.",
        "I am a good person.",
        "I am bold and outgoing.",
        "I stand up for myself without fear.",
        "I am a magnificent, radiant being.",
        "Every day I appreciate myself more and more.",
    ]
]
